#If this file (en_US.lang) is somehow missing it will load any other valid
#.lang file. It's safer to translate the original file change the name and
#have it in the same locale folder, just set new lang name here.
#Lang name formats: https://www.science.co.il/language/Locale-codes.php
lang: "en_US"

settings:
  default-auction-time: 3600 # 60 Minutes by default
  max-auction-price: 2000000000
  max-auction-start: 2000000000
  max-auction-increment: 2000000000
  min-auction-price: 25000
  min-auction-start: 25000
  min-auction-increment: 1
  owner-can-purchase-own: false
  owner-can-bid-own: false
  bid:
    increase-on-bid: true
    increase-amount: 10 #10 Seconds by default

gui:
  confirm:
    title: "&e&lConfirm Purchase"
    items:
      no:
        item: "STAINED_GLASS_PANE:14"
        name: "&C&LNo"
        lore:
          - "&7Do not purchase this item."
      yes:
        item: "STAINED_GLASS_PANE:5"
        name: "&a&lYes"
        lore:
          - "&7Purchase for &a${price}"
  auction:
    title: "&7Auction House"
    items:
      not-enough-money:
        item: "STAINED_GLASS_PANE:14"
        name: "&c&lError"
        lore:
          - "&cYou do not have enough money!"
      guide:
        item: "BOOK:0"
        name: "&e&lGuide"
        lore:
          - "&7This is the auction house, here you can"
          - "&7list items for sale and purchase items"
          - "&7that others have listed for sale."
          - ""
          - "&7The auction is also a great way to make"
          - "&7money by selling farmable items other"
          - "&7players may be interested in buying."
          - ""
          - "&7All sell listings last for a max of &e60 minutes"
          - "&7unsold items are sent to your collection bin."
          - ""
          - "&7Each item is listed as a auction, so"
          - "&7players can out bid each other, or simply"
          - "&7purchase it right away with a set price."
          - ""
          - "&7For more help, use &e/ah help!"
      howtosell:
        item: "GOLD_INGOT:0"
        name: "&e&lHow to Sell"
        lore:
          - "&7To list an item on the auction house, just hold"
          - "&7the item in your hand and type the following command."
          - "&e/ah sell <buyNowPrice> <startPrice> <bidIncrement>"
      yourauctions:
        item: "DIAMOND:0"
        name: "&e&lYour Auctions"
        lore:
          - "&7Click here to view all of the items you"
          - "&7are currently selling on the auction."
          - ""
          - "&e&l{active_player_auctions} Item(s)"
      collectionbin:
        item: "ENDER_CHEST:0"
        name: "&e&lCollection Bin"
        lore:
          - "&7Click here to view and collect all of the"
          - "&7items you have cancelled or have expired."
          - ""
          - "&e&l{expired_player_auctions} Item(s)"
      previouspage:
        item: "PAPER:0"
        name: "&E&L<- Previous Page"
        lore:
          - "&7View the previous page of auctions."
      nextpage:
        item: "PAPER:0"
        name: "&e&lNext Page ->"
        lore:
          - "&7View the next page of auctions."
      refresh:
        item: "CHEST:0"
        name: "&6&lRefresh Auctions"
        lore:
          - "&7Click to refresh the currently"
          - "&7available auction listings."




