name: AuctionHouse
version: ${project.version}
api-version: 1.13
main: com.kiranhart.auctionhouse.Core
authors: [Kiran Hart]
description: The ultimate auction house plugin
website: https://www.kiranhart.com
depends: [ Vault ]

commands:
  auctionhouse:
    description: Main command for the Auction House plugin
    aliases: [ah, auction]